// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/[enterpriseLookup]/_middleware.ts";
import * as $3 from "./routes/api/[enterpriseLookup]/index.ts";
import * as $4 from "./routes/api/[enterpriseLookup]/status.ts";
import * as $5 from "./routes/api/[enterpriseLookup]/users.ts";
import * as $6 from "./routes/api/_middleware.ts";
import * as $7 from "./routes/api/index.ts";
import * as $8 from "./routes/dashboard/jwt.tsx";
import * as $9 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/[enterpriseLookup]/_middleware.ts": $2,
    "./routes/api/[enterpriseLookup]/index.ts": $3,
    "./routes/api/[enterpriseLookup]/status.ts": $4,
    "./routes/api/[enterpriseLookup]/users.ts": $5,
    "./routes/api/_middleware.ts": $6,
    "./routes/api/index.ts": $7,
    "./routes/dashboard/jwt.tsx": $8,
    "./routes/index.tsx": $9,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
